package net.ccfish.jvue.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import net.ccfish.jvue.model.JvueModule;
import net.ccfish.jvue.repository.JvueModuleRepository;
import net.ccfish.jvue.service.JvueModuleService;

/**
 * Generated by Spring Data Generator on 31/01/2018
 */
@Service
@Transactional
public class JvueModuleServiceImpl
        implements JvueModuleService {

    private JvueModuleRepository jvueModuleRepository;

    @Autowired
    public JvueModuleServiceImpl(JvueModuleRepository jvueModuleRepository) {
        this.jvueModuleRepository = jvueModuleRepository;
    }

    @Override
    public JpaRepository<JvueModule, Integer> jpaRepository() {
        return this.jvueModuleRepository;
    }

}
