package net.ccfish.jvue.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import net.ccfish.common.mybatis.BaseMapper;
import net.ccfish.jvue.autogen.dao.JvueUserRoleMapper;
import net.ccfish.jvue.autogen.model.JvueUserRole;
import net.ccfish.jvue.service.JvueUserRoleService;

/**
 * Generated by Spring Data Generator on 31/01/2018
 */
@Service
@Transactional
public class JvueUserRoleServiceImpl implements JvueUserRoleService {

    private JvueUserRoleMapper userRoleMapper;

    @Autowired
    public JvueUserRoleServiceImpl(JvueUserRoleMapper userRoleMapper) {
        this.userRoleMapper = userRoleMapper;
    }

    @Override
    public BaseMapper<JvueUserRole> baseMapper() {
        return this.userRoleMapper;
    }

}
