package net.ccfish.jvue.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import net.ccfish.jvue.model.JvueRole;
import net.ccfish.jvue.repository.JvueRoleRepository;
import net.ccfish.jvue.service.JvueRoleService;

/**
 * Generated by Spring Data Generator on 31/01/2018
 */
@Service
@Transactional
public class JvueRoleServiceImpl implements JvueRoleService {

    private JvueRoleRepository jvueRoleRepository;

    @Autowired
    public JvueRoleServiceImpl(JvueRoleRepository jvueRoleRepository) {
        this.jvueRoleRepository = jvueRoleRepository;
    }

    @Override
    public JpaRepository<JvueRole, Integer> jpaRepository() {
        return this.jvueRoleRepository;
    }

}
