package net.ccfish.jvue.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import net.ccfish.jvue.model.JvueApi;
import net.ccfish.jvue.repository.JvueApiRepository;
import net.ccfish.jvue.service.JvueApiService;

/**
 * Generated by Spring Data Generator on 31/01/2018
 */
@Service
@Transactional
public class JvueApiServiceImpl implements JvueApiService {

    private JvueApiRepository jvueApiRepository;

    @Autowired
    public JvueApiServiceImpl(JvueApiRepository jvueApiRepository) {
        this.jvueApiRepository = jvueApiRepository;
    }

    @Override
    public JpaRepository<JvueApi, Integer> jpaRepository() {
        return this.jvueApiRepository;
    }

}
