package net.ccfish.jvue.service.impl;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import net.ccfish.jvue.model.JvueMenu;
import net.ccfish.jvue.model.JvueModule;
import net.ccfish.jvue.model.JvueRole;
import net.ccfish.jvue.model.JvueSegment;
import net.ccfish.jvue.repository.JvueMenuRepository;
import net.ccfish.jvue.repository.JvueModuleRepository;
import net.ccfish.jvue.repository.JvueRoleRepository;
import net.ccfish.jvue.repository.JvueSegmentRepository;
import net.ccfish.jvue.service.JvueRoleService;
import net.ccfish.jvue.vm.ModuleAndMenus;

/**
 * Generated by Spring Data Generator on 31/01/2018
 */
@Service
@Transactional
public class JvueRoleServiceImpl implements JvueRoleService {

    private JvueRoleRepository jvueRoleRepository;

    @Autowired
    private JvueMenuRepository jvueMenuRepository;

    @Autowired
    private JvueModuleRepository jvueModuleRepository;

    @Autowired
    private JvueSegmentRepository jvueSegmentRepository;

    @Autowired
    public JvueRoleServiceImpl(JvueRoleRepository jvueRoleRepository) {
        this.jvueRoleRepository = jvueRoleRepository;
    }

    @Override
    public JpaRepository<JvueRole, Integer> jpaRepository() {
        return this.jvueRoleRepository;
    }

    @Override
    public ModuleAndMenus findModuleAndMenu(List<Integer> roles) {

        //TODO 根据权限查询对应的菜单和modules/segments
        ModuleAndMenus moduleAndMenus = new ModuleAndMenus();
        List<JvueMenu> menus = jvueMenuRepository.findByParentIdIsNull();

        List<Integer> moduleIds = menus.stream().map(menu -> menu.getModuleId()).distinct()
                .collect(Collectors.toList());

        List<JvueModule> modules = jvueModuleRepository.findAllById(moduleIds);
        List<JvueSegment> segments = jvueSegmentRepository.findAll();
        
        moduleAndMenus.setMenus(menus);
        moduleAndMenus.setModules(modules);
        moduleAndMenus.setSegments(segments);

        return moduleAndMenus;
    }

    /* (non-Javadoc)
     * @see net.ccfish.jvue.service.JvueRoleService#updateEnabled(java.lang.Integer, byte)
     */
    @Override
    public JvueRole updateEnabled(Integer id, byte enabled) {
        
        Optional<JvueRole> jvueRoleOptional = jvueRoleRepository.findById(id);
                
        if (jvueRoleOptional.isPresent()) {
            JvueRole jvueRole = jvueRoleOptional.get();
            jvueRole.setEnabled(enabled);
            return jvueRoleRepository.save(jvueRole);
        }

        return null;
    }


    // TODO
    // 开发/调试模式下，开发者等特殊角色可以无视enabled直接启用，方便调试画面
    
}
