package net.ccfish.jvue.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import net.ccfish.jvue.model.JvueMenu;

/**
* Generated by Spring Data Generator on 31/01/2018
*/
@Repository
public interface JvueMenuRepository extends JpaRepository<JvueMenu, Integer>, JpaSpecificationExecutor<JvueMenu> {

    List<JvueMenu> findByParentIdIsNull();
}
