package net.ccfish.jvue.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import net.ccfish.jvue.model.JvueRoleMenu;

/**
* Generated by Spring Data Generator on 31/01/2018
*/
@Repository
public interface JvueRoleMenuRepository extends JpaRepository<JvueRoleMenu, Integer>, JpaSpecificationExecutor<JvueRoleMenu> {

}
