package net.ccfish.jvue.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import net.ccfish.jvue.model.JvueRoleSegment;

/**
* Generated by Spring Data Generator on 31/01/2018
*/
@Repository
public interface JvueRoleSegmentRepository extends JpaRepository<JvueRoleSegment, Integer>, JpaSpecificationExecutor<JvueRoleSegment> {

}
