package net.ccfish.jvue.repository;

import net.ccfish.jvue.model.JvueSegment;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 31/01/2018
*/
@Repository
public interface JvueSegmentRepository extends JpaRepository<JvueSegment, Integer>, JpaSpecificationExecutor<JvueSegment> {

}
