package net.ccfish.jvue.repository;

import java.util.Collection;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import net.ccfish.jvue.model.UserRole;

/**
* Generated by Spring Data Generator on 31/01/2018
*/
@Repository
public interface UserRoleRepository extends JpaRepository<UserRole, Long>, JpaSpecificationExecutor<UserRole> {

    List<UserRole> findByUserId(Long userId);
    
    void deleteByUserIdAndRoleId(Long userId, Collection<Integer> roleId);
}
